server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8085

spring:
#  datasource:
#    url: jdbc:mysql://${{ DB_ENDPOINT }}:${{ DB_PORT }}/${{ DB_DATABASE_NAME }}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${{ DB_USERNAME }}
#    password: ${{ DB_PASSWORD }}
  datasource:
    url: jdbc:mysql://asset-store.cmbxkvuyugn5.ap-northeast-2.rds.amazonaws.com:3306/asset-store?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: fastcampus1!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.charset_name: UTF-8
  # hibernateLazyInitializer 오류 해결법
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    '[com.phoenix.assetbe]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기

file:
  path: ./upload/ # UPLOAD 폴더 상대경로 / AWS에 S3 사용하는게 좋음