spring:
  profiles:
    active:
      - dev

application:
  mail:
    host: smtp.gmail.com
    username: ${MAIL_FROM_ADDRESS}
    password: ${MAIL_PASSWORD}
    port: 465
    socketFactory-class: javax.net.ssl.SSLSocketFactory
    supplier: gmail.com
    from-mail: ${MAIL_FROM_ADDRESS}
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    default-region: ${AWS_DEFAULT_REGION}
    s3-bucket: ${AWS_S3_BUCKET}
    s3-bucket-url: ${AWS_S3_BUCKET_URL}
