spring:
  profiles:
    active:
      - dev

application:
  mail:
    host: smtp.gmail.com
    username: ${MAIL_FROM_ADDRESS}
    password: ${MAIL_PASSWORD}
    port: 465
    socketFactory-class: javax.net.ssl.SSLSocketFactory
    supplier: gmail.com
    from-mail: ${MAIL_FROM_ADDRESS}