server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: fastcampus1!
    key-store-type: PKCS12
  tomcat:
    uri-encoding: UTF-8
  port: 443
#  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:mysql://asset.cmbxkvuyugn5.ap-northeast-2.rds.amazonaws.com:${RDS_PORT}/${RDS_DATABASE_NAME}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: fastcampus1!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.charset_name: UTF-8

    # db session controller까지 가져오기

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    '[com.phoenix.assetbe]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기